### ISSUE TITLE
Can't use AMQP with non-default vhost and TLS

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/omq#19]
### Describe the bug

Originally reported here:
https://github.com/rabbitmq/omq/commit/64a6f4fe70a73cb692f64cd634196df7ca724a78#commitcomment-141574396

### Reproduction steps

`omq amqp --publisher-uri amqps://..../vhost` -y 0

### Expected behavior

TLS validation should be performed against the hostname, not the vhost

**Comment by mkuratczyk** [comment]
@chadknutson can you test the `main` branch now?

**Comment by johanrhodin** [comment]
I can confirm it works for me with the main branch now (it didn't before)

**Comment by mkuratczyk** [comment]
Thanks. Version 0.4.6 has the fix.
https://github.com/rabbitmq/omq/releases/tag/v0.4.6
https://hub.docker.com/layers/mkuratczyk/omq/0.4.6/images/sha256-17aafd8933f5d2967112c619bc24c6d1507c36c83aff3a38b5bab72e5f9319fc?context=explore

**Comment by chadknutson** [comment]
Thank you very much @mkuratczyk !  
Yes, TLS connections with the vhost specified is working for me now as well.
