### ISSUE TITLE
Unable to install due to go.mod issues

### ISSUE THREAD

**Issue by MirahImage** [rabbitmq/omq#42]
### Describe the bug

When attempting to install omq, golang reports an error due to a replace directive in go.mod.
```
% go install github.com/rabbitmq/omq@main
go: downloading github.com/rabbitmq/omq v0.16.1-0.20241115155757-1ced5aa75f6c
go: github.com/rabbitmq/omq@main (in github.com/rabbitmq/omq@v0.16.1-0.20241115155757-1ced5aa75f6c):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

### Reproduction steps

1. `go install github.com/rabbitmq/omq@latest`
2. Observe error

### Expected behavior

`go install` should succeed

**Comment by mkuratczyk** [comment]
Thanks, I wasn't aware of that. The `replace` clause is there while waiting for https://github.com/Azure/go-amqp/pull/346 to hopefully be merged. As soon as it is - I'll be able to remove it.

The only workaround I'm aware of is using a different installation method for now:
* download a precompiled binary
* clone+build
* or use an OCI image
